"""Generate docs/schema.sql from the SQLAlchemy models (ADR-005).

The models are the authored description of the schema; this renders them as
the readable DDL reference that ships in the repo. Run after any model change:

    uv run python scripts/dump_schema.py

check_schema_drift.sh regenerates and diffs, so a stale file fails CI.

Enum types are emitted explicitly rather than by create_all: the models keep
create_type=False so op.create_table cannot re-create a type the database
already has, and that flag also suppresses the automatic CREATE TYPE here.
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

import app.db.models  # noqa: F401  registers the tables on Base.metadata
from app.db.base import Base

OUT = Path(__file__).resolve().parent.parent.parent / "docs" / "schema.sql"

HEADER = """\
-- ============================================================================
-- TravelWell - system-of-record schema
-- Target: PostgreSQL 15+ (Cloud SQL / AlloyDB)
--
-- GENERATED FILE - do not edit by hand.
-- Source of truth: backend/app/db/models.py (ADR-005).
-- Regenerate: cd backend && uv run python scripts/dump_schema.py
--
-- Operational truth lives in backend/migrations/ (Alembic); this file is the
-- readable reference. CI (backend/scripts/check_schema_drift.sh) regenerates
-- it, applies it to a scratch database and diffs that against the migration
-- chain, so all three stay in step. Change process: edit the models, write a
-- migration, then regenerate this file.
--
-- Design rules this schema encodes:
--   1. Agent state belongs to a Trip, not to a chat session.
--      Every planning/action/event row carries trip_id.
--   2. Reasoning is separated from execution: recommendations live in
--      plan_items/options; anything with a real-world side effect goes
--      through pending_actions (THINK -> PROPOSE -> CONFIRM -> EXECUTE ->
--      VERIFY).
--   3. Provenance is data, not prose: the "How I got here" screen is served
--      from wellness_windows.bounds + plan_item_options (matched prefs,
--      rejection reasons), never re-generated by a model.
--   4. Privacy promise from the design ("I read them, I do not store them"):
--      calendar_events is a minimal trip-relevant cache of derived fields;
--      raw calendar/email payloads are not persisted.
--   5. JSONB only where the shape is genuinely fluid (agent context
--      snapshots, structured outputs, action payloads, event payloads).
--      Everything the UI or scheduler queries by is a typed column.
-- ============================================================================

create extension if not exists pgcrypto;   -- gen_random_uuid()
create extension if not exists citext;
"""


def enums_in_use() -> dict[str, pg.ENUM]:
    """Distinct pg enums, in the order the sorted tables first reach them."""
    found: dict[str, pg.ENUM] = {}
    for table in Base.metadata.sorted_tables:
        for column in table.columns:
            if isinstance(column.type, pg.ENUM):
                found.setdefault(column.type.name, column.type)
    return found


def as_comment(text: str, width: int = 74) -> str:
    return "\n".join("-- " + line for line in textwrap.wrap(text, width))


def with_docs(table: sa.Table, ddl: str) -> str:
    """Re-attach the prose: the class docstring above, column docs inline.

    Both come from `doc=`/`__doc__`, which are Python-side only, so the
    documentation never reaches the database and never becomes drift.
    """
    docs = {c.name: c.doc for c in table.columns if c.doc}
    body = []
    for raw in ddl.replace("\t", "    ").split("\n"):
        line = raw.rstrip()
        head = line.lstrip().split(" ", 1)[0] if line.strip() else ""
        if head in docs:
            line = f"{line}  -- {docs[head]}"
        body.append(line)
    out = "\n".join(body)
    prose = (table.metadata.info.get("docstrings") or {}).get(table.name)
    return f"{as_comment(prose)}\n{out}" if prose else out


def stable(captured: list[tuple[object, str]]) -> list[tuple[object, str]]:
    """Sort each run of CREATE INDEX by name; everything else keeps its place.

    create_all walks Table.indexes, which is a set of objects hashed by memory
    address, so index order varied between this machine and a CI runner.
    """
    ordered: list[tuple[object, str]] = []
    run: list[tuple[object, str]] = []
    for item in captured:
        if isinstance(getattr(item[0], "element", None), sa.Index):
            run.append(item)
            continue
        ordered += sorted(run, key=lambda i: i[0].element.name)
        run = []
        ordered.append(item)
    return ordered + sorted(run, key=lambda i: i[0].element.name)


def render() -> str:
    captured: list[tuple[object, str]] = []
    engine = sa.create_mock_engine(
        "postgresql+psycopg://",
        lambda sql, *a, **kw: captured.append(
            (sql, str(sql.compile(dialect=engine.dialect)).strip())
        ),
    )

    # Table prose lives on the mapped classes, which the Table objects do not
    # point back to; collect it once by table name.
    Base.metadata.info["docstrings"] = {
        m.class_.__tablename__: " ".join((m.class_.__doc__ or "").split())
        for m in Base.registry.mappers
    }

    chunks: list[str] = [section("Enums")]
    for enum_type in enums_in_use().values():
        enum_type.create(engine, checkfirst=False)
    chunks += [f"{text};" for _, text in captured]

    captured.clear()
    Base.metadata.create_all(engine, checkfirst=False)
    chunks.append(section("Tables, indexes and constraints"))
    for sql, text in stable(captured):
        table = getattr(sql, "element", None)
        if isinstance(table, sa.Table):
            text = with_docs(table, text)
        chunks.append(f"{text};")

    return HEADER + "\n" + "\n\n".join(chunks) + "\n"


def section(title: str) -> str:
    rule = "-" * 75
    return f"-- {rule}\n-- {title}\n-- {rule}"


if __name__ == "__main__":
    # --stdout lets the drift check compare without touching the working tree.
    if "--stdout" in sys.argv:
        sys.stdout.write(render())
    else:
        OUT.write_text(render())
        print(f"wrote {OUT}")
