/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Action
         * @description Propose an action. Nothing happens until it is approved.
         */
        post: operations["create_action_api_v1_actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Action
         * @description Polling fallback for the stream, and what the sheet reads on open.
         */
        get: operations["get_action_api_v1_actions__action_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{action_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Action
         * @description Say yes. The executor picks it up from here; this returns immediately.
         *
         *     It does not wait for the booking, because the booking takes as long as the
         *     provider takes. The stream is how the screen follows it.
         */
        post: operations["approve_action_api_v1_actions__action_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{action_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Action Events
         * @description Server-sent events for one action, until it settles.
         *
         *     Polls the row rather than listening, per AGENT_DESIGN.md section 14: the
         *     upgrade to LISTEN/NOTIFY is worth making when the polling cost is real
         *     rather than imagined. Ownership is checked once, here, before the stream
         *     opens - a generator that raised would already have sent 200.
         */
        get: operations["stream_action_events_api_v1_actions__action_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demo Login
         * @description Mint a fresh demo account pre-populated with the demo trips.
         *
         *     Per-tap accounts keep testers isolated (mutations are real and would
         *     collide on a shared account) and build the dates fresh, so the demo never
         *     goes stale. The optional name is just a label, not a credential: the
         *     account lives only in this browser's session cookie.
         *
         *     The email is the one thing this route owns; everything else about the
         *     account is content, and lives in app/services/demo_user/data.py.
         */
        post: operations["demo_login_api_v1_auth_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Email Code */
        post: operations["request_email_code_api_v1_auth_email_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email-code/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email Code */
        post: operations["verify_email_code_api_v1_auth_email_code_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Callback */
        get: operations["oauth_callback_api_v1_auth_oauth__provider__callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Oauth */
        get: operations["start_oauth_api_v1_auth_oauth__provider__start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explore */
        get: operations["explore_api_v1_explore_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Geocode
         * @description Resolve free text to a point.
         *
         *     Written fresh rather than ported: the prototype's /resolve_location is
         *     synchronous and answers with hardcoded Skokie coordinates when no key is
         *     configured, which is worse than an error because the caller cannot tell.
         *     Here the three outcomes stay distinct -- no such place is 404, no key is
         *     503, and a provider failure is 502 -- so nobody plans a trip around a
         *     fallback.
         */
        get: operations["geocode_api_v1_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description Fields on users itself; preferences live on PATCH /me/preferences.
         */
        patch: operations["update_me_api_v1_me_patch"];
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_api_v1_me_preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Preferences */
        patch: operations["update_preferences_api_v1_me_preferences_patch"];
        trace?: never;
    };
    "/me/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connected Sources */
        get: operations["list_connected_sources_api_v1_me_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-items/{item_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Plan Item
         * @description Take a suggestion into the plan.
         */
        post: operations["accept_plan_item_api_v1_plan_items__item_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-items/{item_id}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan Item Provenance
         * @description "How I got here", served from stored rows and never regenerated.
         *
         *     Unlike PlanItem.options this includes the rejected candidates: they are
         *     read-only here, which is exactly why they are safe to show.
         */
        get: operations["get_plan_item_provenance_api_v1_plan_items__item_id__provenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-items/{item_id}/select-option": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Select Plan Item Option
         * @description Choose which option the item uses. Status is untouched: picking a place
         *     is not the same act as accepting the suggestion, and the review card lets
         *     someone swap and only then keep.
         */
        post: operations["select_plan_item_option_api_v1_plan_items__item_id__select_option_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-items/{item_id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skip Plan Item
         * @description Decline an item. `remove` is the stronger form: skipped means not this
         *     time, removed is a tombstone the agent should not re-offer.
         */
        post: operations["skip_plan_item_api_v1_plan_items__item_id__skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips_api_v1_trips_get"];
        put?: never;
        /** Create Trip */
        post: operations["create_trip_api_v1_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["get_trip_api_v1_trips__trip_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Trip */
        post: operations["confirm_trip_api_v1_trips__trip_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss Trip
         * @description "Not a trip". Detection is noisy, so the gate has to open both ways.
         */
        post: operations["dismiss_trip_api_v1_trips__trip_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip Plan */
        get: operations["get_trip_plan_api_v1_trips__trip_id__plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}/plan/accept-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept All Plan Items
         * @description Answer every open item at once, the way `Accept all` reads.
         *
         *     Items needing a reservation still land on `planned`, not `awaiting_user`:
         *     booking is its own gate later, and the review summary is what tells the
         *     user a reservation is still coming. Accepting is not agreeing to book.
         */
        post: operations["accept_all_plan_items_api_v1_trips__trip_id__plan_accept_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip Timeline */
        get: operations["get_trip_timeline_api_v1_trips__trip_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip Today */
        get: operations["get_trip_today_api_v1_trips__trip_id__today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionCreateIn
         * @description Propose an action. What it will do is assembled server-side.
         *
         *     The client names the act and the item, not the place: letting a request
         *     carry its own place and time would make the endpoint a way to book
         *     anything at all, rather than a way to book the plan the user is looking at.
         *     `payload` is the small set of choices that are genuinely the user's.
         */
        ActionCreateIn: {
            action_type: components["schemas"]["ActionType"];
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Plan Item Id */
            plan_item_id?: string | null;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
        };
        /**
         * ActionFailureOut
         * @description Why an action did not complete, in terms the user can act on.
         *
         *     `alternatives` is in the contract and not here: suggesting other places
         *     needs the places cache, which is Slice 6. Serving an empty list would say
         *     "we looked and found nothing", which is not what happened.
         */
        ActionFailureOut: {
            /** Code */
            code: string;
            /** External Url */
            external_url?: string | null;
            /** Message */
            message: string;
        };
        /**
         * ActionStatus
         * @enum {string}
         */
        ActionStatus: "proposed" | "approved" | "executing" | "completed" | "failed" | "canceled";
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: "make_reservation" | "cancel_reservation" | "create_calendar_event" | "update_calendar_event" | "delete_calendar_event" | "send_invite";
        /** ApproveIn */
        ApproveIn: {
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AuthProvider
         * @enum {string}
         */
        AuthProvider: "google" | "apple" | "email";
        /** CalendarEventSummaryOut */
        CalendarEventSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location Name */
            location_name?: string | null;
            /** Title */
            title: string;
        };
        /** ConnectedSourceOut */
        ConnectedSourceOut: {
            /**
             * Connected At
             * Format: date-time
             */
            connected_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["SourceKind"];
            /** Last Synced At */
            last_synced_at?: string | null;
            status: components["schemas"]["SourceStatus"];
        };
        /** DemoLoginRequest */
        DemoLoginRequest: {
            /** Name */
            name?: string | null;
        };
        /** EmailCodeRequest */
        EmailCodeRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** EmailCodeVerify */
        EmailCodeVerify: {
            /** Code */
            code: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * ExploreAnchorOut
         * @description Where the map opens and what distances are measured from.
         */
        ExploreAnchorOut: {
            /** Is Hotel */
            is_hotel: boolean;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Name */
            name: string;
        };
        /**
         * ExploreKindOut
         * @description A category chip. The count is over the whole radius, not the filter, so
         *     switching chips never changes the other chips' numbers.
         */
        ExploreKindOut: {
            /** Count */
            count: number;
            kind: components["schemas"]["PlaceKind"];
        };
        /** ExploreOut */
        ExploreOut: {
            anchor?: components["schemas"]["ExploreAnchorOut"] | null;
            /** Kinds */
            kinds: components["schemas"]["ExploreKindOut"][];
            /** Places */
            places: components["schemas"]["ExplorePlaceOut"][];
            /** Radius M */
            radius_m: number;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
        };
        /**
         * ExplorePlaceOut
         * @description One card and one pin: the list and the map read the same row.
         *
         *     The first four derived fields are computed per request against this user's
         *     preferences and this trip's anchor, so two users looking at the same cached
         *     place see different reasons for it.
         */
        ExplorePlaceOut: {
            /** Address */
            address?: string | null;
            /** Amenities */
            amenities: string[];
            /** Day Pass Cents */
            day_pass_cents?: number | null;
            /** Distance Meters */
            distance_meters?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["PlaceKind"];
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Matched Preferences */
            matched_preferences: string[];
            /** Name */
            name: string;
            /** Over Budget Reason */
            over_budget_reason?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Price Level */
            price_level?: number | null;
            reservable_via?: components["schemas"]["ReservationProvider"] | null;
            /** Summary */
            summary?: string | null;
            /** Walk Minutes */
            walk_minutes?: number | null;
        };
        /**
         * ItemKind
         * @enum {string}
         */
        ItemKind: "activity" | "meal";
        /**
         * ItemStatus
         * @enum {string}
         */
        ItemStatus: "suggested" | "awaiting_user" | "planned" | "confirmed" | "working" | "changed" | "skipped" | "removed";
        /** ItemTokenIn */
        ItemTokenIn: {
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * NeedsYouKind
         * @description Which gate the open work belongs to, so a row can name the ask.
         * @enum {string}
         */
        NeedsYouKind: "plan" | "approval" | "mixed";
        /**
         * OptionState
         * @enum {string}
         */
        OptionState: "selected" | "alternative" | "rejected";
        /** PendingActionOut */
        PendingActionOut: {
            action_type: components["schemas"]["ActionType"];
            failure?: components["schemas"]["ActionFailureOut"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Plan Item Id */
            plan_item_id?: string | null;
            reservation?: components["schemas"]["ReservationOut"] | null;
            status: components["schemas"]["ActionStatus"];
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PlaceKind
         * @enum {string}
         */
        PlaceKind: "workout" | "food" | "outdoor" | "recovery" | "lodging";
        /** PlanItemOptionOut */
        PlanItemOptionOut: {
            /** Display Name */
            display_name: string;
            /** Display Summary */
            display_summary?: string | null;
            /** Distance Minutes */
            distance_minutes?: number | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Matched Preferences */
            matched_preferences: string[];
            /** Reason */
            reason?: string | null;
            /** Rejection Reason */
            rejection_reason?: string | null;
            state: components["schemas"]["OptionState"];
        };
        /** PlanItemOut */
        PlanItemOut: {
            /** Ends At */
            ends_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["ItemKind"];
            /** Needs Reservation */
            needs_reservation: boolean;
            /** Options */
            options: components["schemas"]["PlanItemOptionOut"][];
            reservation?: components["schemas"]["ReservationOut"] | null;
            selected_option?: components["schemas"]["PlanItemOptionOut"] | null;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            status: components["schemas"]["ItemStatus"];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Why */
            why: string[];
            window?: components["schemas"]["WellnessWindowOut"] | null;
            /** Window Id */
            window_id?: string | null;
        };
        /** PlanOut */
        PlanOut: {
            /** Headline */
            headline: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: components["schemas"]["PlanItemOut"][];
            /** Provenance Summary */
            provenance_summary?: string | null;
            status: components["schemas"]["PlanStatus"];
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /**
         * PlanProgress
         * @description The one badge a trip row carries. `none` renders as no badge at all.
         * @enum {string}
         */
        PlanProgress: "none" | "preparing" | "planned" | "booking";
        /**
         * PlanStatus
         * @enum {string}
         */
        PlanStatus: "draft" | "proposed" | "partially_accepted" | "accepted" | "superseded";
        /** PreferencesOut */
        PreferencesOut: {
            /** Activities */
            activities: string[];
            /** Allow Auto Book */
            allow_auto_book: boolean;
            /** Allow Calendar Write */
            allow_calendar_write: boolean;
            /** Amenities */
            amenities: string[];
            /** Day Pass Budget Cents */
            day_pass_budget_cents?: number | null;
            /** Dietary */
            dietary: string[];
            /** Memberships */
            memberships: string[];
            /** Preferred Times */
            preferred_times: string[];
            /** Price Level Max */
            price_level_max?: number | null;
            /** Session Max Minutes */
            session_max_minutes?: number | null;
            /** Session Min Minutes */
            session_min_minutes?: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Watch Schedule */
            watch_schedule: boolean;
        };
        /**
         * PreferencesUpdateIn
         * @description Partial update: only fields present in the body are applied
         *     (model_dump(exclude_unset=True)); explicit null clears a nullable scalar.
         *     Defaults below are never used, they only make every field optional.
         */
        PreferencesUpdateIn: {
            /** Activities */
            activities?: string[];
            /**
             * Allow Auto Book
             * @default false
             */
            allow_auto_book?: boolean;
            /**
             * Allow Calendar Write
             * @default false
             */
            allow_calendar_write?: boolean;
            /** Amenities */
            amenities?: string[];
            /** Day Pass Budget Cents */
            day_pass_budget_cents?: number | null;
            /** Dietary */
            dietary?: string[];
            /** Memberships */
            memberships?: string[];
            /** Preferred Times */
            preferred_times?: string[];
            /** Price Level Max */
            price_level_max?: number | null;
            /** Session Max Minutes */
            session_max_minutes?: number | null;
            /** Session Min Minutes */
            session_min_minutes?: number | null;
            /**
             * Watch Schedule
             * @default true
             */
            watch_schedule?: boolean;
        };
        /**
         * ProblemOut
         * @description The error body, declared so it reaches the generated contract.
         *
         *     Rendered by an exception handler rather than returned from a route, so
         *     FastAPI cannot infer it; app/api/router.py attaches it to every operation
         *     as the default response. problem_response() below builds from this model,
         *     which is what keeps the declaration and the wire body the same shape.
         */
        ProblemOut: {
            /**
             * Code
             * @description Stable machine code the client maps to a failure state.
             */
            code: string;
            /** Detail */
            detail?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /**
         * ProvenanceOut
         * @description "How I got here": the opening, and every candidate considered for it.
         */
        ProvenanceOut: {
            /** Considered */
            considered: components["schemas"]["PlanItemOptionOut"][];
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            window?: components["schemas"]["WellnessWindowOut"] | null;
        };
        /**
         * ReservationOut
         * @description A booking attempted for an item.
         *
         *     `failure_reason` was withheld while nothing could be done about a refusal.
         *     Retrying is now a second action against the same item, so the reason is
         *     what the user acts on, and a booking that says only "refused" makes the
         *     retry a guess.
         */
        ReservationOut: {
            /** Confirmation Code */
            confirmation_code?: string | null;
            /** External Url */
            external_url?: string | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Party Size */
            party_size: number;
            provider: components["schemas"]["ReservationProvider"];
            /** Reserved For */
            reserved_for?: string | null;
            status: components["schemas"]["ReservationStatus"];
        };
        /**
         * ReservationProvider
         * @enum {string}
         */
        ReservationProvider: "travelwell" | "opentable" | "external_link";
        /**
         * ReservationStatus
         * @enum {string}
         */
        ReservationStatus: "pending" | "holding" | "confirmed" | "failed" | "canceled";
        /**
         * ResolvedLocationOut
         * @description Free text resolved to a point. `query` is echoed so a client that fired
         *     several lookups can tell the answers apart.
         */
        ResolvedLocationOut: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Name */
            name: string;
            /** Query */
            query: string;
            /** Timezone */
            timezone?: string | null;
        };
        /** SelectOptionIn */
        SelectOptionIn: {
            /**
             * Option Id
             * Format: uuid
             */
            option_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SkipIn */
        SkipIn: {
            /**
             * Remove
             * @default false
             */
            remove?: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "google_calendar" | "gmail" | "apple_calendar" | "manual_import";
        /**
         * SourceStatus
         * @enum {string}
         */
        SourceStatus: "connected" | "error" | "revoked";
        /** SourcesOut */
        SourcesOut: {
            /** Sources */
            sources: components["schemas"]["ConnectedSourceOut"][];
        };
        /** TimelineEntryOut */
        TimelineEntryOut: {
            calendar_event?: components["schemas"]["CalendarEventSummaryOut"] | null;
            /** Ends At */
            ends_at?: string | null;
            /** Entry Type */
            entry_type: string;
            plan_item?: components["schemas"]["PlanItemOut"] | null;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
        };
        /** TimelineOut */
        TimelineOut: {
            /** Entries */
            entries: components["schemas"]["TimelineEntryOut"][];
        };
        /** TodayViewOut */
        TodayViewOut: {
            /** Day Label */
            day_label: string;
            /** Next Up */
            next_up: components["schemas"]["PlanItemOut"][];
            /** State Detail */
            state_detail?: string | null;
            /** State Word */
            state_word: string;
            /** Timezone */
            timezone: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            window?: components["schemas"]["WellnessWindowOut"] | null;
        };
        /** TripConfirmIn */
        TripConfirmIn: {
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TripCreateIn */
        TripCreateIn: {
            /** Destination Name */
            destination_name: string;
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
            /** Label */
            label?: string | null;
            /** Lodging Name */
            lodging_name?: string | null;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
        };
        /** TripEvidenceOut */
        TripEvidenceOut: {
            /** Detail */
            detail?: string | null;
            /** Kind */
            kind: string;
            source: components["schemas"]["SourceKind"];
            /** Summary */
            summary: string;
        };
        /** TripListOut */
        TripListOut: {
            /** Trips */
            trips: components["schemas"]["TripOut"][];
        };
        /**
         * TripOrigin
         * @enum {string}
         */
        TripOrigin: "calendar_detection" | "manual" | "import";
        /** TripOut */
        TripOut: {
            /** Destination Name */
            destination_name: string;
            /** Detection Confidence */
            detection_confidence?: number | null;
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
            /** Evidence */
            evidence: components["schemas"]["TripEvidenceOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label?: string | null;
            /** Needs You Count */
            needs_you_count: number;
            needs_you_kind?: components["schemas"]["NeedsYouKind"] | null;
            origin: components["schemas"]["TripOrigin"];
            plan_progress: components["schemas"]["PlanProgress"];
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            state: components["schemas"]["TripState"];
            /** State Line */
            state_line: string;
            /** Timezone */
            timezone: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TripState
         * @enum {string}
         */
        TripState: "detected" | "confirmed" | "upcoming" | "preparing" | "active" | "completed" | "archived" | "dismissed";
        /** UserOut */
        UserOut: {
            auth_provider: components["schemas"]["AuthProvider"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email: string;
            /** Home Timezone */
            home_timezone: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** UserUpdateIn */
        UserUpdateIn: {
            /** Display Name */
            display_name?: string | null;
            /** Home Timezone */
            home_timezone?: string | null;
        };
        /** WellnessWindowOut */
        WellnessWindowOut: {
            /** Bounds */
            bounds: components["schemas"]["WindowBoundOut"][];
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Gap Explanation */
            gap_explanation?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            status: components["schemas"]["WindowStatus"];
        };
        /** WindowBoundOut */
        WindowBoundOut: {
            /** Detail */
            detail?: string | null;
            /** Source Label */
            source_label?: string | null;
            /** Tag */
            tag: string;
            /** Title */
            title: string;
        };
        /**
         * WindowStatus
         * @enum {string}
         */
        WindowStatus: "open" | "filled" | "expired" | "superseded";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_action_api_v1_actions_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingActionOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_action_api_v1_actions__action_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingActionOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    approve_action_api_v1_actions__action_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingActionOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    stream_action_events_api_v1_actions__action_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    demo_login_api_v1_auth_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DemoLoginRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    request_email_code_api_v1_auth_email_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    verify_email_code_api_v1_auth_email_code_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailCodeVerify"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    oauth_callback_api_v1_auth_oauth__provider__callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    start_oauth_api_v1_auth_oauth__provider__start_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    explore_api_v1_explore_get: {
        parameters: {
            query: {
                trip_id: string;
                category?: components["schemas"]["PlaceKind"] | null;
                query?: string | null;
                radius_m?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExploreOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    geocode_api_v1_geocode_get: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedLocationOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    update_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_preferences_api_v1_me_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    update_preferences_api_v1_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    list_connected_sources_api_v1_me_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    accept_plan_item_api_v1_plan_items__item_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemTokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanItemOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_plan_item_provenance_api_v1_plan_items__item_id__provenance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvenanceOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    select_plan_item_option_api_v1_plan_items__item_id__select_option_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectOptionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanItemOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    skip_plan_item_api_v1_plan_items__item_id__skip_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanItemOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    list_trips_api_v1_trips_get: {
        parameters: {
            query?: {
                state?: components["schemas"]["TripState"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripListOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    create_trip_api_v1_trips_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_trip_api_v1_trips__trip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    confirm_trip_api_v1_trips__trip_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    dismiss_trip_api_v1_trips__trip_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_trip_plan_api_v1_trips__trip_id__plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    accept_all_plan_items_api_v1_trips__trip_id__plan_accept_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_trip_timeline_api_v1_trips__trip_id__timeline_get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_trip_today_api_v1_trips__trip_id__today_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayViewOut"];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
}
