/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime configuration for the web client */
        get: operations["getRuntimeConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a one-time sign-in code to an email address */
        post: operations["requestEmailCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email-code/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange an email code for an httpOnly session cookie */
        post: operations["verifyEmailCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin an OAuth sign-in (server-side redirect flow, BFF pattern) */
        get: operations["startOauth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the session cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trips for the current user, with derived "needs you" counts */
        get: operations["listTrips"];
        put?: never;
        /** Create a trip manually */
        post: operations["createTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A single trip with its evidence */
        get: operations["getTrip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm a detected trip */
        post: operations["confirmTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The Today view for a trip (window card, next-up items, state line) */
        get: operations["getTripToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar events and plan items interleaved by time */
        get: operations["getTripTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current plan (versioned) with its items and selected options */
        get: operations["getTripPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-items/{itemId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a suggested item into the plan */
        post: operations["acceptPlanItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-items/{itemId}/select-option": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Swap the selected option for an item (no data loss, flips option_state) */
        post: operations["selectPlanItemOption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-items/{itemId}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Skip or remove an item */
        post: operations["skipPlanItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-items/{itemId}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** "How I got here": window bounds, matched preferences, rejected options */
        get: operations["getPlanItemProvenance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose an action (reservation, calendar write) for approval */
        post: operations["createAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{actionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A pending action (polling fallback for the SSE stream) */
        get: operations["getAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{actionId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a proposed action for execution */
        post: operations["approveAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{actionId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE stream of an executing action's progress
         * @description text/event-stream. Event types: `trace` (purposeful progress copy),
         *     `status` (action_status change), `result` (terminal payload), `error`.
         *     Data payloads follow StreamEvent.
         */
        get: operations["streamActionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a user event (voice, text, or UI intent) to the agent event spine
         * @description Voice, text, and taps are the same pipeline; nothing invokes the agent directly.
         */
        post: operations["submitEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An agent run (polling fallback for the SSE stream) */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE stream of a live agent run
         * @description text/event-stream, the re-homed version of the prototype's proven
         *     /api/events/{session_id} channel. Event types: `trace`, `status`,
         *     `result` (structured run output, never markdown), `error`.
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Place candidates for the Explore map, filtered by category and preferences */
        get: operations["explore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resolve_location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve a free-text location to coordinates (kept from the prototype) */
        get: operations["resolveLocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wellness preferences and autonomy toggles */
        get: operations["getPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update preferences (partial) */
        patch: operations["updatePreferences"];
        trace?: never;
    };
    "/me/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connected calendar/email sources with real connection status */
        get: operations["listConnectedSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notification inbox */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}/opened": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record that a notification was opened (deep-link tracking) */
        post: operations["markNotificationOpened"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AuthProvider: "google" | "apple" | "email";
        /** @enum {string} */
        SourceKind: "google_calendar" | "gmail" | "apple_calendar" | "manual_import";
        /** @enum {string} */
        SourceStatus: "connected" | "error" | "revoked";
        /** @enum {string} */
        TripState: "detected" | "confirmed" | "upcoming" | "preparing" | "active" | "completed" | "archived" | "dismissed";
        /** @enum {string} */
        TripOrigin: "calendar_detection" | "manual" | "import";
        /** @enum {string} */
        PlaceKind: "workout" | "food" | "outdoor" | "recovery" | "lodging";
        /** @enum {string} */
        WindowStatus: "open" | "filled" | "expired" | "superseded";
        /** @enum {string} */
        PlanStatus: "draft" | "proposed" | "partially_accepted" | "accepted" | "superseded";
        /** @enum {string} */
        ItemStatus: "suggested" | "awaiting_user" | "planned" | "confirmed" | "working" | "changed" | "skipped" | "removed";
        /** @enum {string} */
        ItemKind: "activity" | "meal";
        /** @enum {string} */
        OptionState: "selected" | "alternative" | "rejected";
        /** @enum {string} */
        ReservationProvider: "travelwell" | "opentable" | "external_link";
        /** @enum {string} */
        ReservationStatus: "pending" | "holding" | "confirmed" | "failed" | "canceled";
        /** @enum {string} */
        ActionType: "make_reservation" | "cancel_reservation" | "create_calendar_event" | "update_calendar_event" | "delete_calendar_event" | "send_invite";
        /** @enum {string} */
        ActionStatus: "proposed" | "approved" | "executing" | "completed" | "failed" | "canceled";
        /** @enum {string} */
        EventKind: "scheduled_activation" | "scheduled_daily" | "user_text" | "user_voice" | "ui_action" | "calendar_changed" | "trip_changed" | "reservation_changed" | "external_context";
        /** @enum {string} */
        RunKind: "pretrip_plan" | "replan_conflict" | "user_request" | "reservation_flow" | "daily_checkin" | "trip_detection";
        /** @enum {string} */
        RunStatus: "running" | "completed" | "failed" | "canceled";
        /** @enum {string} */
        NotificationStatus: "pending" | "sent" | "opened" | "dismissed";
        Problem: {
            /** Format: uri */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            /** @description Stable machine code the client maps to honest failure states (e.g. reservation_declined). */
            code: string;
        };
        RuntimeConfig: {
            api_base_url: string;
            maps_browser_key?: string;
            /** @description VAPID/FCM public key for Web Push subscription. */
            push_public_key?: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name?: string;
            auth_provider: components["schemas"]["AuthProvider"];
            /** Format: date-time */
            created_at: string;
        };
        TripCreate: {
            destination_name: string;
            /** Format: date */
            starts_on: string;
            /** Format: date */
            ends_on: string;
            lodging_name?: string;
        };
        Trip: {
            /** Format: uuid */
            id: string;
            state: components["schemas"]["TripState"];
            origin: components["schemas"]["TripOrigin"];
            destination_name: string;
            /** @description IANA zone; all trip times render in this zone, never the device zone. */
            timezone: string;
            /** Format: date */
            starts_on: string;
            /** Format: date */
            ends_on: string;
            detection_confidence?: number;
            /** @description "Based on" rows for the detection card. */
            evidence?: components["schemas"]["TripEvidence"][];
            /** @description Real trust indicator ("Active - watching your schedule"), server-derived. */
            state_line?: string;
            /** @description Derived from open plan_items / pending_actions; never computed client-side. */
            needs_you_count: number;
            /** Format: date-time */
            updated_at: string;
        };
        TripEvidence: {
            source: components["schemas"]["SourceKind"];
            summary: string;
        };
        TodayView: {
            /** Format: uuid */
            trip_id: string;
            /** @description Server-derived ("Day 2 of 4 - Chicago"). */
            day_label: string;
            state_word: string;
            timezone: string;
            window?: components["schemas"]["WellnessWindow"];
            next_up: components["schemas"]["PlanItem"][];
        };
        WellnessWindow: {
            status: components["schemas"]["WindowStatus"];
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /** @description The calendar constraints that define the window ("after your 3pm review"). */
            bounds: string[];
        };
        TimelineEntry: {
            /** @enum {string} */
            entry_type: "calendar_event" | "plan_item";
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at?: string;
            calendar_event?: components["schemas"]["CalendarEventSummary"];
            plan_item?: components["schemas"]["PlanItem"];
        };
        CalendarEventSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            location_name?: string;
        };
        Plan: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            trip_id: string;
            version: number;
            status: components["schemas"]["PlanStatus"];
            headline: string;
            items: components["schemas"]["PlanItem"][];
            /** Format: date-time */
            updated_at: string;
        };
        PlanItem: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["ItemKind"];
            status: components["schemas"]["ItemStatus"];
            title: string;
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
            /** @description Matched preferences served from plan_item_options.matched_preferences. */
            why?: string[];
            selected_option?: components["schemas"]["PlanItemOption"];
            reservation?: components["schemas"]["Reservation"];
            /** Format: date-time */
            updated_at: string;
        };
        PlanItemOption: {
            /** Format: uuid */
            id: string;
            state: components["schemas"]["OptionState"];
            place: components["schemas"]["Place"];
            matched_preferences?: string[];
            /** @description Required by schema CHECK when state = rejected. */
            rejection_reason?: string;
        };
        Provenance: {
            /** Format: uuid */
            item_id: string;
            window: components["schemas"]["WellnessWindow"];
            /** @description All options including rejected ones with their stored rejection_reason. */
            considered: components["schemas"]["PlanItemOption"][];
        };
        Place: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["PlaceKind"];
            name: string;
            rating?: number;
            distance_meters?: number;
            walk_minutes?: number;
            price_level?: number;
            lat?: number;
            lng?: number;
            /** Format: uri */
            photo_url?: string;
            /** Format: uri */
            external_url?: string;
        };
        ResolvedLocation: {
            query: string;
            name: string;
            lat: number;
            lng: number;
            timezone?: string;
        };
        ActionCreate: {
            action_type: components["schemas"]["ActionType"];
            /** Format: uuid */
            trip_id: string;
            /** Format: uuid */
            plan_item_id?: string;
            /** @description Action-type-specific parameters (e.g. reservation time, party size). */
            payload?: {
                [key: string]: unknown;
            };
        };
        PendingAction: {
            /** Format: uuid */
            id: string;
            action_type: components["schemas"]["ActionType"];
            status: components["schemas"]["ActionStatus"];
            /** Format: uuid */
            trip_id: string;
            /** Format: uuid */
            plan_item_id?: string;
            /** @description What / when / where / cost rows for the confirm sheet, server-assembled. */
            summary?: {
                [key: string]: unknown;
            };
            failure?: components["schemas"]["ActionFailure"];
            reservation?: components["schemas"]["Reservation"];
            /** Format: date-time */
            updated_at: string;
        };
        ActionFailure: {
            code: string;
            message: string;
            alternatives?: components["schemas"]["Place"][];
            /**
             * Format: uri
             * @description Honest fallback ("book directly") when the provider declines.
             */
            external_url?: string;
        };
        Reservation: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["ReservationStatus"];
            provider: components["schemas"]["ReservationProvider"];
            /** @description Present iff status = confirmed (schema CHECK); the UI holds the same line. */
            confirmation_code?: string;
            /** Format: date-time */
            reserved_for?: string;
            /** Format: uri */
            external_url?: string;
        };
        EventCreate: {
            kind: components["schemas"]["EventKind"];
            /** Format: uuid */
            trip_id?: string;
            /** @description Kind-specific payload (transcript text, UI intent name, etc.). */
            payload: {
                [key: string]: unknown;
            };
        };
        RunRef: {
            /** Format: uuid */
            event_id: string;
            /**
             * Format: uuid
             * @description Present when the event started (or joined) an agent run.
             */
            run_id?: string;
        };
        AgentRun: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["RunKind"];
            status: components["schemas"]["RunStatus"];
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at?: string;
            /** @description Structured run output (plan diff, cards); never free-form markdown. */
            result?: {
                [key: string]: unknown;
            };
        };
        /** @description Envelope for SSE payloads on run and action streams. */
        StreamEvent: {
            /** @enum {string} */
            event: "trace" | "status" | "result" | "error";
            data: {
                [key: string]: unknown;
            };
        };
        Preferences: {
            allow_reservations: boolean;
            allow_calendar_writes: boolean;
            allow_notifications: boolean;
            workout_kinds?: string[];
            dietary?: string[];
            pace?: string;
            /** Format: date-time */
            updated_at: string;
        };
        PreferencesUpdate: {
            allow_reservations?: boolean;
            allow_calendar_writes?: boolean;
            allow_notifications?: boolean;
            workout_kinds?: string[];
            dietary?: string[];
            pace?: string;
        };
        ConnectedSource: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["SourceKind"];
            status: components["schemas"]["SourceStatus"];
            /** Format: date-time */
            connected_at?: string;
        };
        Notification: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["NotificationStatus"];
            title: string;
            body: string;
            cta?: {
                label: string;
                /** @description In-app route the notification opens (routes/ owns the URL contract). */
                deep_link: string;
            };
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: {
        /** @description RFC 9457 problem details with a stable machine code */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The entity changed since the client last read it (agent replan, another device). Refetch and re-present. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        TripId: string;
        ItemId: string;
        ActionId: string;
        RunId: string;
        /** @description Client-generated UUID; mirrors pending_actions.idempotency_key so retries are safe. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRuntimeConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime config (also emitted as /config.json by entrypoint.sh) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfig"];
                };
            };
        };
    };
    requestEmailCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Code sent (or silently accepted for unknown addresses) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    verifyEmailCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    code: string;
                };
            };
        };
        responses: {
            /** @description Session established; Set-Cookie carries the httpOnly session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    startOauth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "google";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the provider's consent screen */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listTrips: {
        parameters: {
            query?: {
                state?: components["schemas"]["TripState"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trips ordered by start date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        trips: components["schemas"]["Trip"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createTrip: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated UUID; mirrors pending_actions.idempotency_key so retries are safe. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreate"];
            };
        };
        responses: {
            /** @description Created trip (state = confirmed, origin = manual) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The trip */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    confirmTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date-time */
                    updated_at: string;
                };
            };
        };
        responses: {
            /** @description Trip confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            409: components["responses"]["Conflict"];
            default: components["responses"]["Problem"];
        };
    };
    getTripToday: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Today view assembled server-side in the trip's timezone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayView"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTripTimeline: {
        parameters: {
            query?: {
                /** @description Trip-local date (YYYY-MM-DD); omitted = whole trip */
                day?: string;
            };
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline entries ordered by start time */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entries: components["schemas"]["TimelineEntry"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTripPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    acceptPlanItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date-time */
                    updated_at: string;
                };
            };
        };
        responses: {
            /** @description Updated item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanItem"];
                };
            };
            409: components["responses"]["Conflict"];
            default: components["responses"]["Problem"];
        };
    };
    selectPlanItemOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    option_id: string;
                    /** Format: date-time */
                    updated_at: string;
                };
            };
        };
        responses: {
            /** @description Updated item with the newly selected option */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanItem"];
                };
            };
            409: components["responses"]["Conflict"];
            default: components["responses"]["Problem"];
        };
    };
    skipPlanItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date-time */
                    updated_at: string;
                    /** @default false */
                    remove?: boolean;
                };
            };
        };
        responses: {
            /** @description Updated item (status = skipped or removed) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanItem"];
                };
            };
            409: components["responses"]["Conflict"];
            default: components["responses"]["Problem"];
        };
    };
    getPlanItemProvenance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provenance served from stored data, never generated client-side */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provenance"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createAction: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated UUID; mirrors pending_actions.idempotency_key so retries are safe. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionCreate"];
            };
        };
        responses: {
            /** @description Proposed action */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingAction"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actionId: components["parameters"]["ActionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The action */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingAction"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    approveAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actionId: components["parameters"]["ActionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date-time */
                    updated_at: string;
                };
            };
        };
        responses: {
            /** @description Action approved (status = approved, then executing) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingAction"];
                };
            };
            409: components["responses"]["Conflict"];
            default: components["responses"]["Problem"];
        };
    };
    streamActionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actionId: components["parameters"]["ActionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    submitEvent: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated UUID; mirrors pending_actions.idempotency_key so retries are safe. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Event accepted; if it starts a run, the reference is returned */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRef"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    explore: {
        parameters: {
            query: {
                trip_id: string;
                category?: components["schemas"]["PlaceKind"];
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Surfaced candidates (cached server-side in places) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        places: components["schemas"]["Place"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    resolveLocation: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Best-effort geocoding result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedLocation"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Updated preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listConnectedSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sources: components["schemas"]["ConnectedSource"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notifications, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        notifications: components["schemas"]["Notification"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    markNotificationOpened: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
}
