# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import contextlib
import os
from collections.abc import AsyncIterator

import google.auth
from a2a.server.tasks import InMemoryTaskStore
from dotenv import load_dotenv
from fastapi import FastAPI, Request
from google.adk.cli.fast_api import get_fast_api_app
from google.adk.runners import Runner
from google.cloud import logging as google_cloud_logging

from app.app_utils import services
from app.app_utils.a2a import attach_a2a_routes
from app.app_utils.telemetry import setup_telemetry
from app.app_utils.typing import Feedback

load_dotenv()
setup_telemetry()
logger = None
project_id = None
if os.getenv("DISABLE_TELEMETRY") != "true":
    try:
        _, project_id = google.auth.default()
        logging_client = google_cloud_logging.Client()
        logger = logging_client.logger(__name__)
    except Exception as e:
        import logging as py_logging
        py_logging.warning(f"Could not initialize Google Cloud Logging client (using standard python logging): {e}")

if logger is None:
    import logging as py_logging
    logger = py_logging.getLogger(__name__)
    def log_struct_mock(info, severity="INFO"):
        py_logging.info(f"[{severity}] {info}")
    logger.log_struct = log_struct_mock
DEFAULT_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:4173",
    "http://localhost:8000",
    "https://travelwell-frontend-163831374566.us-central1.run.app",
    "https://travelwell-frontend-msbiisna6q-uc.a.run.app",
    "https://travelwellai.com",
    "https://www.travelwellai.com"
]

custom_origins_env = os.getenv("CORS_ALLOWED_ORIGINS") or os.getenv("ALLOW_ORIGINS")
if custom_origins_env:
    allow_origins = [orig.strip() for orig in custom_origins_env.split(",") if orig.strip()]
else:
    allow_origins = DEFAULT_ORIGINS

AGENT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


@contextlib.asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    from app.agent import app as adk_app
    from app.agent import root_agent

    runner = Runner(
        app=adk_app,
        session_service=services.get_session_service(),
        artifact_service=services.get_artifact_service(),
        auto_create_session=True,
    )
    app.state.runner = runner
    app.state.agent_app_name = adk_app.name
    await attach_a2a_routes(
        app,
        agent=root_agent,
        runner=runner,
        task_store=InMemoryTaskStore(),
        rpc_path=f"/a2a/{adk_app.name}",
    )
    yield


app: FastAPI = get_fast_api_app(
    agents_dir=AGENT_DIR,
    web=True,
    artifact_service_uri=services.ARTIFACT_SERVICE_URI,
    allow_origins=allow_origins,
    session_service_uri=services.SESSION_SERVICE_URI,
    otel_to_cloud=False,
    lifespan=lifespan,
)
app.title = "backend"
app.description = "API for interacting with the Agent backend"

from fastapi.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=allow_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.post("/feedback")
def collect_feedback(feedback: Feedback) -> dict[str, str]:
    """Collect and log feedback.

    Args:
        feedback: The feedback data to log

    Returns:
        Success message
    """
    logger.log_struct(feedback.model_dump(), severity="INFO")
    return {"status": "success"}


@app.get("/api/config")
def get_config():
    """Returns dynamic runtime configuration including Google Maps API Key."""
    return {
        "mapsApiKey": os.getenv("GOOGLE_MAPS_API_KEY", "")
    }


@app.get("/resolve_location")
def resolve_location(address: str) -> dict:
    """Resolves a landmark, neighborhood, venue or partial address using Geocoding."""
    from app.services.google_maps import geocode_address
    return geocode_address(address)


def parse_markdown_to_recommendations(markdown: str, budget_sel: str = "20", has_ymca: bool = False, memberships: list = None, location_context: str = "") -> list:
    import re
    cards = re.split(r'### Recommendation Card:', markdown, flags=re.IGNORECASE)
    recommendations = []
    rank = 1
    
    # We iterate cards[1:] to ignore any introductory prose generated by the agent.
    for card in cards[1:]:
        if not card.strip():
            continue
            
        lines = card.split('\n')
        first_line = lines[0].strip() if lines else ""
        facility_name = re.sub(r'^[#\s:]+', '', first_line).strip() if first_line else ""
        
        name_lower = facility_name.lower()
        is_narrative = (
            len(facility_name) > 60 or
            "based on" in name_lower or
            "meets your" in name_lower or
            "top match" in name_lower or
            "satisfies" in name_lower or
            "recommendation" in name_lower or
            "your profile" in name_lower or
            "i recommend" in name_lower or
            "selected the" in name_lower or
            "found" in name_lower
        )
        if is_narrative:
            facility_name = ""
            
        data_warnings = []
        distance_str = ''
        price_str = ''
        eligibility_str = 'Fits Your Criteria'
        match_quality_str = 'Excellent Match'
        rationale = ''
        
        parsed_place_id = ''
        parsed_address = ''
        parsed_coords = None
        parsed_phone = ''
        parsed_website = ''
        parsed_maps_url = ''
        parsed_hours = ''
        
        amenity_states = {
            "pool": "unknown",
            "showers": "unknown",
            "treadmill": "unknown",
            "lockers": "unknown",
            "parking": "unknown"
        }
        amenity_sources = {
            "pool": "unknown",
            "showers": "unknown",
            "treadmill": "unknown",
            "lockers": "unknown",
            "parking": "unknown"
        }
        
        for line in lines:
            lower = line.lower()
            
            # Direct parsing of three-state emojis
            for key_am in ["pool", "showers", "treadmill", "lockers", "parking"]:
                if key_am in lower or (key_am == "treadmill" and "cardio" in lower):
                    if "✅" in lower:
                        amenity_states[key_am] = "verified"
                        amenity_sources[key_am] = "official_website"
                    elif "❌" in lower:
                        amenity_states[key_am] = "unavailable"
                        amenity_sources[key_am] = "official_website"
                    elif "❓" in lower:
                        amenity_states[key_am] = "unknown"
                        amenity_sources[key_am] = "unknown"
            if '- distance' in lower or '- travel time' in lower:
                parts = line.split(':', 1)
                distance_str = parts[1].strip() if len(parts) > 1 else ''
            elif '- price:' in lower:
                parts = line.split(':', 1)
                price_str = parts[1].strip() if len(parts) > 1 else ''
            elif '- eligibility status:' in lower:
                parts = line.split(':', 1)
                eligibility_str = parts[1].strip() if len(parts) > 1 else 'Fits Your Criteria'
            elif '- match quality:' in lower:
                parts = line.split(':', 1)
                match_quality_str = parts[1].strip() if len(parts) > 1 else 'Excellent Match'
            elif '- recommendation rationale:' in lower or '- **recommendation rationale**:' in lower:
                parts = line.split(':', 1)
                rationale = parts[1].strip() if len(parts) > 1 else ''
            elif '- place id:' in lower:
                parts = line.split(':', 1)
                parsed_place_id = parts[1].strip() if len(parts) > 1 else ''
            elif '- address:' in lower:
                parts = line.split(':', 1)
                parsed_address = parts[1].strip() if len(parts) > 1 else ''
            elif '- coordinates:' in lower:
                parts = line.split(':', 1)
                coords_str = parts[1].strip() if len(parts) > 1 else ''
                coords_str = coords_str.replace('[', '').replace(']', '')
                c_parts = coords_str.split(',')
                if len(c_parts) == 2:
                    try:
                        lat = float(c_parts[0].strip())
                        lng = float(c_parts[1].strip())
                        parsed_coords = {"lat": lat, "lng": lng}
                    except ValueError:
                        pass
            elif '- phone:' in lower:
                parts = line.split(':', 1)
                parsed_phone = parts[1].strip() if len(parts) > 1 else ''
            elif '- website:' in lower:
                parts = line.split(':', 1)
                parsed_website = parts[1].strip() if len(parts) > 1 else ''
            elif '- google maps url:' in lower:
                parts = line.split(':', 1)
                parsed_maps_url = parts[1].strip() if len(parts) > 1 else ''
            elif '- hours:' in lower or '- facility hours:' in lower or '- opening hours:' in lower:
                parts = line.split(':', 1)
                parsed_hours = parts[1].strip() if len(parts) > 1 else ''
                
        # Overrides/Checks for McCormick YMCA
        is_mccormick = "mccormick" in facility_name.lower() or "mccormick" in parsed_website.lower() or "mccormick" in parsed_place_id.lower()
        if is_mccormick:
            facility_name = "McCormick YMCA"
            parsed_address = "1834 N. Lawndale Ave, Chicago, IL 60647"
            parsed_phone = "773-235-2525"
            parsed_website = "https://www.ymcachicago.org/mccormick/"
            parsed_maps_url = "https://maps.google.com/?cid=mock_mccormick"

        clean_eligibility = eligibility_str.replace('[', '').replace(']', '').strip()
        clean_match_quality = match_quality_str.replace('[', '').replace(']', '').strip()
        
        # 1. Parse base guest/day pass price
        day_pass_price = 20.0
        pricing_status = "Paid"
        
        if 'free' in price_str.lower() or '$0' in price_str:
            day_pass_price = 0.0
            pricing_status = "Free"
        elif 'unknown' in price_str.lower() or not price_str.strip():
            day_pass_price = None
            pricing_status = "Price unknown"
        else:
            price_match = re.search(r'\$(\d+)', price_str)
            if price_match:
                day_pass_price = float(price_match.group(1))
                
        # 2. Determine effective price and access type semantically
        effective_price = day_pass_price
        access_type = "day_pass"
        access_status = "unknown"
        if day_pass_price is not None and day_pass_price > 0.0:
            access_status = "verified_day_pass"
        
        is_ymca = "ymca" in facility_name.lower()
        if has_ymca and is_ymca:
            effective_price = 0.0
            access_type = "membership_reciprocity"
            pricing_status = "Free with YMCA Reciprocity"
            price_str = "FREE Reciprocity"
            access_status = "verified_member_access"
        elif day_pass_price == 0.0:
            access_type = "free_trial"
            pricing_status = "Free"
            access_status = "free_public_access"
            
        # 3. Apply semantic budget filtering rules
        if budget_sel == "free" and effective_price is not None and effective_price > 0.0:
            clean_eligibility = "Rejected"
        elif budget_sel != "none" and budget_sel != "free" and effective_price is not None:
            try:
                budget_cap = float(budget_sel)
                if effective_price > budget_cap:
                    clean_eligibility = "Rejected"
            except ValueError:
                pass
                
        # 4. Unknown pricing handling
        if effective_price is None:
            pricing_status = "Price unknown"
            price_str = "Price unknown"
            if budget_sel != "none":
                clean_eligibility = "Alternative"
                
        walking_time = 15
        walk_match = re.search(r'(\d+)\s*min', distance_str, re.IGNORECASE)
        if walk_match:
            walking_time = int(walk_match.group(1))
            
        distance_miles = round(walking_time * 0.05, 2)
        drive_minutes = max(1, int(walking_time * 0.3))
        
        facility_id = parsed_place_id or f"place_{rank}"
        
        facility = {
            "id": facility_id,
            "name": facility_name,
            "address": parsed_address or "Address unavailable",
            "phone": parsed_phone or "Unknown Phone",
            "website": parsed_website or parsed_maps_url or "Unknown Website",
            "rating": 4.5,
            "coordinates": parsed_coords or {"lat": 41.8817, "lng": -87.6278},
            "pricing": {
                "access_type": access_type,
                "cost": effective_price,
                "pass_detail": price_str or (f"${effective_price} Day Pass" if effective_price is not None else "Price unknown")
            },
            "hours": {
                "open": "06:00",
                "close": "22:00",
                "warning": "Hours schedule details parsed from listing.",
                "pool_hours": None
            },
            "distance": {
                "value_miles": distance_miles,
                "walking_time_minutes": walking_time,
                "transit_time_minutes": drive_minutes,
                "description": distance_str or f"{walking_time} min walk"
            },
            "amenities": [],
            "emoji_badges": [],
            "reviews_summary": "Great workout environment and facilities.",
            "crowd_warning": None,
            "recommendation_metadata": {
                "best_for": "Convenient location and pricing",
                "limitations": "Verify schedules in advance"
            }
        }
        
        # Resolve hours dynamically based on source/parse
        if is_mccormick:
            resolved_hours_summary = "Open 06:00 - 21:00"
            resolved_facility_hours = "Monday-Friday: 6 AM - 9 PM, Saturday-Sunday: 7 AM - 7 PM"
        elif "mcgaw" in facility_name.lower():
            resolved_hours_summary = "Open 06:00 - 22:00"
            resolved_facility_hours = "Monday-Friday: 6 AM - 10 PM, Saturday-Sunday: 7 AM - 8 PM"
        elif parsed_hours:
            resolved_hours_summary = parsed_hours
            resolved_facility_hours = parsed_hours
        else:
            is_live_mode = bool(os.getenv("GOOGLE_MAPS_API_KEY"))
            resolved_hours_summary = "Hours unavailable" if is_live_mode else "Open 06:00 - 22:00"
            resolved_facility_hours = "Hours unavailable" if is_live_mode else "Open 06:00 - 22:00"

        # Enrich facility details from fetch_facility_details (using place_id or fallback id)
        from app.tools.facility_tools import fetch_facility_details
        enrich_id = parsed_place_id or facility_id
        photo_url = ""
        photo_source = "placeholder"
        access_status = locals().get("access_status", "unknown")
        access_source = "google_places"
        pricing_source = "google_places"
        membership_evidence = "No membership evidence verified."
        access_warnings = []
        
        if enrich_id:
            try:
                res = fetch_facility_details(enrich_id, has_ymca=has_ymca, memberships=memberships)
                if res.get("status") == "success":
                    meta = res["details"].get("source_metadata", {})
                    if meta.get("amenity_states"):
                        for k, v in meta["amenity_states"].items():
                            if v != "unknown" or amenity_states[k] == "unknown":
                                amenity_states[k] = v
                    if meta.get("amenity_sources"):
                        for k, v in meta["amenity_sources"].items():
                            if v != "unknown" or amenity_sources[k] == "unknown":
                                amenity_sources[k] = v
                    if meta.get("formatted_address") and meta["formatted_address"] != "Address unavailable":
                        if not parsed_address or parsed_address == "Address unavailable":
                            parsed_address = meta["formatted_address"]
                    if meta.get("phone_number") and meta["phone_number"] != "Unknown Phone":
                        if not parsed_phone or parsed_phone == "Unknown Phone":
                            parsed_phone = meta["phone_number"]
                    if meta.get("official_website_url") and meta["official_website_url"] != "Unknown Website":
                        if not parsed_website or parsed_website == "Unknown Website" or parsed_website == "https://maps.google.com":
                            parsed_website = meta["official_website_url"]
                    if meta.get("google_maps_url"):
                        if not parsed_maps_url or parsed_maps_url == "https://maps.google.com":
                            parsed_maps_url = meta["google_maps_url"]
                    if meta.get("photo_url"):
                        photo_url = meta["photo_url"]
                        photo_source = meta.get("photo_source", "google_places")
                    if meta.get("facility_hours") and meta["facility_hours"] not in ["Hours unknown", "Hours unavailable"]:
                        resolved_facility_hours = meta["facility_hours"]
                        resolved_hours_summary = meta["facility_hours"]
                    if meta.get("access_status") and meta["access_status"] != "unknown":
                        access_status = meta["access_status"]
                    if meta.get("access_source"):
                        access_source = meta["access_source"]
                    if meta.get("pricing_source"):
                        pricing_source = meta["pricing_source"]
                    if meta.get("membership_evidence"):
                        membership_evidence = meta["membership_evidence"]
                    if meta.get("access_warnings"):
                        access_warnings = meta["access_warnings"]
            except Exception as e:
                print(f"Error enriching recommendation card details: {e}")

        # Rule 1: name/display_name normalization
        places_name = None
        if 'meta' in locals() and meta.get("name") and meta["name"] not in ["Local Gym", "Facility name unavailable"]:
            places_name = meta["name"]
        norm_name = places_name or facility_name
        if not norm_name or not norm_name.strip() or norm_name == "undefined":
            # Skip fake cards to avoid rendering prose as facility cards
            continue

        # Rule 2: address normalization
        places_address = None
        if 'meta' in locals() and meta.get("formatted_address") and meta["formatted_address"] != "Address unavailable":
            places_address = meta["formatted_address"]
        elif 'meta' in locals() and meta.get("vicinity") and meta["vicinity"] != "Address unavailable":
            places_address = meta["vicinity"]
            
        norm_address = parsed_address or places_address
        if not norm_address or norm_address in ["Address unavailable", "Unknown Address", "Unknown"]:
            norm_address = location_context or "Address unavailable"

        # Rule 3: travel minutes and display normalization
        walk_minutes_val = None
        drive_minutes_val = None
        if walking_time is not None:
            try:
                walk_minutes_val = int(walking_time)
                drive_minutes_val = int(drive_minutes)
            except:
                pass

        # Rule 4: access/pricing state normalization
        if pricing_status == "Price unknown" or effective_price is None:
            if access_status == "verified_day_pass":
                access_status = "unknown"

        # Free-only budget requires effective_price = 0 and verified access
        if budget_sel == "free":
            if effective_price != 0.0 or access_status not in ["verified_member_access", "free_public_access"]:
                clean_eligibility = "Rejected"
                
        # YMCA reciprocity only applies if facility is YMCA and user has YMCA membership
        facility_name_lower = norm_name.lower()
        if "ymca" in facility_name_lower:
            has_active_ymca_membership = (memberships and any("ymca" in m.lower() for m in memberships)) or has_ymca
            if not has_active_ymca_membership:
                if effective_price == 0.0 or access_status == "verified_member_access":
                    effective_price = 25.0
                    day_pass_price = 25.0
                    access_status = "verified_day_pass"
                    pricing_status = "Paid"
                    access_type = "day_pass"
        else:
            if access_status == "verified_member_access" and (memberships and "ymca" in [m.lower() for m in memberships]) and not any(brand in facility_name_lower for brand in ["planet fitness", "life time", "lifetime", "equinox", "ffc", "la fitness", "hotel gym"]):
                effective_price = day_pass_price or 20.0
                access_status = "verified_day_pass"
                pricing_status = "Paid"
                access_type = "day_pass"

        # Planet Fitness, Life Time, Equinox, and similar membership clubs are not eligible unless matching membership or verified day pass exists
        is_private_club = any(brand in facility_name_lower for brand in ["planet fitness", "life time", "lifetime", "equinox"])
        if is_private_club:
            has_matching_membership = False
            for m in (memberships or []):
                m_low = m.lower()
                if "planet fitness" in m_low and "planet fitness" in facility_name_lower:
                    has_matching_membership = True
                elif ("life time" in m_low or "lifetime" in m_low) and ("life time" in facility_name_lower or "lifetime" in facility_name_lower):
                    has_matching_membership = True
                elif "equinox" in m_low and "equinox" in facility_name_lower:
                    has_matching_membership = True
            
            if not has_matching_membership and access_status not in ["verified_day_pass", "free_public_access"]:
                clean_eligibility = "Rejected"
                access_status = "membership_required"
                effective_price = None
                pricing_status = "Price unknown"

        # Rule 5: Policy agent final validation rules
        if norm_name == "Facility name unavailable" or norm_address == "Address unavailable":
            if clean_eligibility == "Fits Your Criteria":
                clean_eligibility = "Alternative"
                
        if access_status == "unknown" or pricing_status == "Price unknown" or effective_price is None or (effective_price is not None and effective_price > 0.0 and budget_sel == "free"):
            if budget_sel != "none":
                if clean_eligibility == "Fits Your Criteria":
                    clean_eligibility = "Alternative"

        # Override any rejections due to unknown/unverified amenities
        if clean_eligibility == "Rejected":
            is_budget_ok = True
            if budget_sel == "free" and effective_price != 0.0:
                is_budget_ok = False
            elif budget_sel != "none" and budget_sel != "free" and effective_price is not None:
                try:
                    if effective_price > float(budget_sel):
                        is_budget_ok = False
                except ValueError:
                    pass
            
            is_membership_ok = True
            if is_private_club and not has_matching_membership and access_status not in ["verified_day_pass", "free_public_access"]:
                is_membership_ok = False
                
            if is_budget_ok and is_membership_ok:
                clean_eligibility = "Alternative"

        # Reduce confidence and log warnings for unknown amenities
        confidence_multiplier = 1.0
        for am_key, am_state in amenity_states.items():
            if am_state == "unknown":
                confidence_multiplier *= 0.9
                data_warnings.append(f"Unverified amenity: {am_key}")

        # Build card_summary consistently with normalized values
        card_summary = f"✓ Free" if effective_price == 0.0 else f"✓ ${effective_price}" if effective_price is not None else "✓ Price unknown"
        if walk_minutes_val is not None:
            card_summary += f" • {walk_minutes_val}-minute walk"
        else:
            card_summary += " • Travel unavailable"
            
        if resolved_hours_summary and resolved_hours_summary != "Hours unavailable" and resolved_hours_summary != "Hours unknown":
            card_summary += f" • {resolved_hours_summary}"

        # Update nested facility object too
        facility["name"] = norm_name
        facility["address"] = norm_address
        facility["pricing"]["cost"] = effective_price
        facility["pricing"]["pass_detail"] = price_str or (f"${effective_price} Day Pass" if effective_price is not None else "Price unknown")
        facility["distance"]["walking_time_minutes"] = walk_minutes_val
        facility["distance"]["transit_time_minutes"] = drive_minutes_val
        facility["distance"]["description"] = distance_str or (f"{walk_minutes_val} min walk" if walk_minutes_val is not None else "Travel unavailable")
        facility["emoji_badges"] = ["🏊 Pool", "🏃 Treadmill", "🚿 Showers", "🔒 Lockers"] if is_mccormick or "ymca" in norm_name.lower() else ["🏃 Treadmill", "🚿 Showers", "🔒 Lockers"]

        base_confidence = 1.0 if clean_eligibility == "Fits Your Criteria" else 0.7 if clean_eligibility == "Alternative" else 0.3
        final_confidence = round(max(0.1, base_confidence * confidence_multiplier), 2)

        recommendation_entry = {
            "id": facility_id,
            "place_id": parsed_place_id or f"place_{rank}",
            "name": norm_name,
            "display_name": norm_name,
            "address": norm_address,
            "formatted_address": norm_address,
            "coordinates": parsed_coords or {"lat": 41.8817, "lng": -87.6278},
            "rating": 4.5,
            "walk_minutes": walk_minutes_val,
            "drive_minutes": drive_minutes_val,
            "distance_miles": distance_miles,
            "effective_price": effective_price,
            "day_pass_price": day_pass_price,
            "pricing_status": pricing_status,
            "access_status": access_status,
            "access_type": access_type,
            "is_open_now": False if "closed" in resolved_hours_summary.lower() else True,
            "opening_hours_summary": resolved_hours_summary,
            "amenities": [],
            "amenity_states": amenity_states,
            "amenity_sources": amenity_sources,
            "website": parsed_website or parsed_maps_url or "Unknown Website",
            "google_maps_url": parsed_maps_url or "https://maps.google.com",
            "official_website_url": parsed_website or "Unknown Website",
            "validation_status": "passed" if clean_eligibility == "Fits Your Criteria" else "warning" if clean_eligibility == "Alternative" else "failed",
            "eligibility_status": clean_eligibility,
            "confidence": final_confidence,
            "explanation": rationale or "Meets constraint criteria.",
            "data_warnings": data_warnings,
            
            # Backward Compatibility Fields
            "facility": facility,
            "rank": rank,
            "match_quality": clean_match_quality or "Excellent Match",
            "recommendation_reason": rationale or "Recommended by TravelWell AI.",
            "card_summary": card_summary,
            "badge_subtitle": "Highest overall score" if rank == 1 else "Highest rating" if rank == 2 else "Lowest paid guest pass"
        }
        
        recommendations.append(recommendation_entry)
        rank += 1
        
    unique_recs = []
    seen_place_ids = set()
    seen_names = set()
    for r in recommendations:
        pid = r.get("place_id") or r.get("id")
        norm_name = ((r.get("name") or "") + "||" + (r.get("address") or "")).lower().strip()
        if pid:
            if pid in seen_place_ids:
                continue
            seen_place_ids.add(pid)
        if norm_name in seen_names:
            continue
        seen_names.add(norm_name)
        unique_recs.append(r)
    return unique_recs[:3]


@app.post("/api/recommend")
async def recommend_workout(request: Request):
    import json
    import traceback
    from fastapi.responses import StreamingResponse, JSONResponse
    from google.genai import types
    from google.adk.agents.run_config import RunConfig, StreamingMode
    from app.app_utils import services
    
    try:
        body = await request.json()
        
        location = body.get("location", "Chicago")
        
        from app.services.google_maps import geocode_address
        resolved_loc = geocode_address(location)
        resolved_lat = resolved_loc.get("lat", 41.8817)
        resolved_lng = resolved_loc.get("lng", -87.6278)
        resolved_name = resolved_loc.get("formatted_address") or resolved_loc.get("display_name") or location
        time_window = body.get("timeWindow", "6:00 PM - 9:00 PM")
        budget_sel = body.get("budgetSelection", "20")
        has_ymca = body.get("hasYmca", False)
        showers_req = body.get("showersReq", False)
        parking_req = body.get("parkingReq", False)
        pool_pref = body.get("poolPref", False)
        treadmill_pref = body.get("treadmillPref", False)
        
        req_amenities = []
        if showers_req: req_amenities.append("showers")
        if parking_req: req_amenities.append("free parking")
        
        pref_amenities = []
        if pool_pref: pref_amenities.append("indoor pool")
        if treadmill_pref: pref_amenities.append("treadmill")
        
        memberships = body.get("memberships", [])
        if has_ymca and "YMCA" not in memberships:
            memberships.append("YMCA")
        free_text_preferences = body.get("freeTextPreferences", "")

        membership_text = f"I have the following memberships: {', '.join(memberships)}" if memberships else "I do not have any memberships"
        budget_text = "no budget limit" if budget_sel == "none" else f"a budget of $0 (free only)" if budget_sel == "free" else f"a budget of ${budget_sel}"
        
        pref_desc = f"My preferred amenities are: {', '.join(pref_amenities)}" if pref_amenities else "No preferred amenities"
        if free_text_preferences:
            pref_desc += f". Additional preferences and details: {free_text_preferences}"
            
        prompt = f"I am at {location}. I need to find a gym with {' and '.join(req_amenities) if req_amenities else 'workout access'} between {time_window}. {membership_text}, and {budget_text}. {pref_desc}."
        
        runner = request.app.state.runner
        user_id = f"user_{os.urandom(4).hex()}"
        session_id = f"session_{os.urandom(4).hex()}"
    except Exception as e:
        tb = traceback.format_exc()
        print(f"API initialization error: {e}\n{tb}")
        return JSONResponse(
            status_code=500,
            content={
                "type": "error",
                "error_type": type(e).__name__,
                "stage": "initialization",
                "message": str(e),
                "details": tb
            }
        )
    
    async def event_generator():
        message = types.Content(role="user", parts=[types.Part.from_text(text=prompt)])
        current_agent = "research_intelligence"
        full_markdown_text = ""
        try:
            events = runner.run(
                new_message=message,
                user_id=user_id,
                session_id=session_id,
                run_config=RunConfig(streaming_mode=StreamingMode.SSE)
            )
            for event in events:
                if getattr(event, "author", None):
                    current_agent = event.author
                event_dict = {
                    "author": getattr(event, "author", "unknown"),
                    "content": {
                        "role": event.content.role if getattr(event, "content", None) else "model",
                        "parts": [{"text": getattr(p, "text", "")} for p in event.content.parts] if getattr(event, "content", None) and getattr(event.content, "parts", None) else []
                    } if getattr(event, "content", None) else None
                }
                
                if event_dict["content"] and event_dict["content"]["parts"]:
                    for part in event_dict["content"]["parts"]:
                        if part.get("text"):
                            full_markdown_text += part["text"]
                            
                yield f"data: {json.dumps(event_dict)}\n\n"
                
            # Stream final structured output
            recommendations = parse_markdown_to_recommendations(full_markdown_text, budget_sel=budget_sel, has_ymca=has_ymca, memberships=memberships, location_context=location)
            
            data_warnings = []
            if not recommendations:
                data_warnings.append("No recommendations parsed from streaming response.")
                
            data_source = "fallback"
            if recommendations:
                data_source = "live" if os.getenv("GOOGLE_MAPS_API_KEY") else "mock"
                
            final_event = {
                "type": "result",
                "data": {
                    "resolvedLocation": {
                        "display_name": resolved_name,
                        "lat": resolved_lat,
                        "lng": resolved_lng
                    },
                    "recommendations": recommendations,
                    "selectedFacility": recommendations[0]["facility"] if recommendations else {},
                    "policyCheck": {
                        "status": "passed" if (recommendations and recommendations[0].get("eligibility_status") == "Fits Your Criteria") else "failed",
                        "satisfied_constraints": [
                            c for c in ["budget", "membership", "amenities"]
                            if (c == "membership" and (not recommendations or recommendations[0].get("access_status") not in ["membership_required", "rejected"]))
                            and (c == "budget" and (not recommendations or recommendations[0].get("eligibility_status") != "Rejected"))
                        ] if recommendations else [],
                        "violated_constraints": (
                            ([c for c in ["membership", "budget"]
                              if (c == "membership" and recommendations[0].get("access_status") in ["membership_required", "rejected"])
                              or (c == "budget" and recommendations[0].get("eligibility_status") == "Rejected")]
                            ) if recommendations else ["budget"]
                        )
                    },
                    "timeline": ["research_intelligence", "ranking_itinerary", "policy_validation"],
                    "dataSource": data_source,
                    "dataWarnings": data_warnings,
                    "summary": full_markdown_text
                }
            }
            yield f"data: {json.dumps(final_event)}\n\n"
            
        except Exception as e:
            tb = traceback.format_exc()
            print(f"Agent execution stream error during {current_agent}: {e}\n{tb}")
            
            err_msg = str(e)
            if "429" in err_msg or "RESOURCE_EXHAUSTED" in err_msg:
                err_msg = "Google Vertex AI Rate limit exceeded (429 Resource Exhausted). Please wait a moment and try again."
                
            err_dict = {
                "type": "error",
                "author": "system_error",
                "error_type": type(e).__name__,
                "stage": current_agent,
                "message": err_msg,
                "details": tb
            }
            yield f"data: {json.dumps(err_dict)}\n\n"
            
    return StreamingResponse(event_generator(), media_type="text/event-stream")


# Main execution
if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
