/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShellAgentRouteImport } from './routes/_shell.agent'
import { Route as ShellExploreRouteImport } from './routes/_shell.explore'
import { Route as ShellTodayRouteImport } from './routes/_shell.today'
import { Route as ShellTripRouteImport } from './routes/_shell.trip'
import { Route as ShellTripTripIdRouteImport } from './routes/_shell.trip_.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAgentRoute = ShellAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExploreRoute = ShellExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTodayRoute = ShellTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTripRoute = ShellTripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTripTripIdRoute = ShellTripTripIdRouteImport.update({
  id: '/trip_/$tripId',
  path: '/trip/$tripId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/agent': typeof ShellAgentRoute
  '/explore': typeof ShellExploreRoute
  '/today': typeof ShellTodayRoute
  '/trip': typeof ShellTripRoute
  '/trip/$tripId': typeof ShellTripTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/agent': typeof ShellAgentRoute
  '/explore': typeof ShellExploreRoute
  '/today': typeof ShellTodayRoute
  '/trip': typeof ShellTripRoute
  '/trip/$tripId': typeof ShellTripTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/_shell/agent': typeof ShellAgentRoute
  '/_shell/explore': typeof ShellExploreRoute
  '/_shell/today': typeof ShellTodayRoute
  '/_shell/trip': typeof ShellTripRoute
  '/_shell/trip_/$tripId': typeof ShellTripTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/sign-in'
    | '/agent'
    | '/explore'
    | '/today'
    | '/trip'
    | '/trip/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/sign-in'
    | '/agent'
    | '/explore'
    | '/today'
    | '/trip'
    | '/trip/$tripId'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/profile'
    | '/sign-in'
    | '/_shell/agent'
    | '/_shell/explore'
    | '/_shell/today'
    | '/_shell/trip'
    | '/_shell/trip_/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/agent': {
      id: '/_shell/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof ShellAgentRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/explore': {
      id: '/_shell/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ShellExploreRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/today': {
      id: '/_shell/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof ShellTodayRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/trip': {
      id: '/_shell/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof ShellTripRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/trip_/$tripId': {
      id: '/_shell/trip_/$tripId'
      path: '/trip/$tripId'
      fullPath: '/trip/$tripId'
      preLoaderRoute: typeof ShellTripTripIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAgentRoute: typeof ShellAgentRoute
  ShellExploreRoute: typeof ShellExploreRoute
  ShellTodayRoute: typeof ShellTodayRoute
  ShellTripRoute: typeof ShellTripRoute
  ShellTripTripIdRoute: typeof ShellTripTripIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAgentRoute: ShellAgentRoute,
  ShellExploreRoute: ShellExploreRoute,
  ShellTodayRoute: ShellTodayRoute,
  ShellTripRoute: ShellTripRoute,
  ShellTripTripIdRoute: ShellTripTripIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
