-- ============================================================================
-- TravelWell - system-of-record schema
-- Target: PostgreSQL 15+ (Cloud SQL / AlloyDB)
--
-- GENERATED FILE - do not edit by hand.
-- Source of truth: backend/app/db/models.py (ADR-005).
-- Regenerate: cd backend && uv run python scripts/dump_schema.py
--
-- Operational truth lives in backend/migrations/ (Alembic); this file is the
-- readable reference. CI (backend/scripts/check_schema_drift.sh) regenerates
-- it, applies it to a scratch database and diffs that against the migration
-- chain, so all three stay in step. Change process: edit the models, write a
-- migration, then regenerate this file.
--
-- Design rules this schema encodes:
--   1. Agent state belongs to a Trip, not to a chat session.
--      Every planning/action/event row carries trip_id.
--   2. Reasoning is separated from execution: recommendations live in
--      plan_items/options; anything with a real-world side effect goes
--      through pending_actions (THINK -> PROPOSE -> CONFIRM -> EXECUTE ->
--      VERIFY).
--   3. Provenance is data, not prose: the "How I got here" screen is served
--      from wellness_windows.bounds + plan_item_options (matched prefs,
--      rejection reasons), never re-generated by a model.
--   4. Privacy promise from the design ("I read them, I do not store them"):
--      calendar_events is a minimal trip-relevant cache of derived fields;
--      raw calendar/email payloads are not persisted.
--   5. JSONB only where the shape is genuinely fluid (agent context
--      snapshots, structured outputs, action payloads, event payloads).
--      Everything the UI or scheduler queries by is a typed column.
-- ============================================================================

create extension if not exists pgcrypto;   -- gen_random_uuid()
create extension if not exists citext;

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

CREATE TYPE area_fill_outcome AS ENUM ('ok', 'error', 'unavailable');

CREATE TYPE place_kind AS ENUM ('workout', 'food', 'outdoor', 'recovery', 'lodging');

CREATE TYPE reservation_provider AS ENUM ('travelwell', 'opentable', 'external_link');

CREATE TYPE auth_provider AS ENUM ('google', 'apple', 'email');

CREATE TYPE source_kind AS ENUM ('google_calendar', 'gmail', 'apple_calendar', 'manual_import');

CREATE TYPE source_status AS ENUM ('connected', 'error', 'revoked');

CREATE TYPE trip_state AS ENUM ('detected', 'confirmed', 'upcoming', 'preparing', 'active', 'completed', 'archived', 'dismissed');

CREATE TYPE trip_origin AS ENUM ('calendar_detection', 'manual', 'import');

CREATE TYPE event_kind AS ENUM ('scheduled_activation', 'scheduled_daily', 'user_text', 'user_voice', 'ui_action', 'calendar_changed', 'trip_changed', 'reservation_changed', 'external_context');

CREATE TYPE event_disposition AS ENUM ('pending', 'dropped_no_trip', 'dropped_immaterial', 'accepted');

CREATE TYPE window_status AS ENUM ('open', 'filled', 'expired', 'superseded');

CREATE TYPE run_kind AS ENUM ('pretrip_plan', 'replan_conflict', 'user_request', 'reservation_flow', 'daily_checkin', 'trip_detection');

CREATE TYPE run_status AS ENUM ('running', 'completed', 'failed', 'canceled');

CREATE TYPE notification_status AS ENUM ('pending', 'sent', 'opened', 'dismissed');

CREATE TYPE plan_status AS ENUM ('draft', 'proposed', 'partially_accepted', 'accepted', 'superseded');

CREATE TYPE item_kind AS ENUM ('activity', 'meal');

CREATE TYPE item_status AS ENUM ('suggested', 'awaiting_user', 'planned', 'confirmed', 'working', 'changed', 'skipped', 'removed');

CREATE TYPE action_type AS ENUM ('make_reservation', 'cancel_reservation', 'create_calendar_event', 'update_calendar_event', 'delete_calendar_event', 'send_invite');

CREATE TYPE action_status AS ENUM ('proposed', 'approved', 'executing', 'completed', 'failed', 'canceled');

CREATE TYPE option_state AS ENUM ('selected', 'alternative', 'rejected');

CREATE TYPE reservation_status AS ENUM ('pending', 'holding', 'confirmed', 'failed', 'canceled');

-- ---------------------------------------------------------------------------
-- Tables, indexes and constraints
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    user_id UUID DEFAULT gen_random_uuid() NOT NULL,
    email CITEXT NOT NULL,
    display_name TEXT,
    auth_provider auth_provider NOT NULL,
    home_timezone TEXT DEFAULT 'UTC'::text NOT NULL,  -- IANA name
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (user_id),
    UNIQUE (email)
);

-- One live email sign-in code per address; only the code's HMAC is stored.
-- No FK to users: a code is issued before the account may exist.
CREATE TABLE login_codes (
    email CITEXT NOT NULL,
    code_hmac TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    attempts_left SMALLINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (email)
);

-- Venue cache; the provider stays authoritative and rows age out by TTL.
CREATE TABLE places (
    place_id UUID DEFAULT gen_random_uuid() NOT NULL,
    provider_ref TEXT,  -- Google place_id
    kind place_kind NOT NULL,
    name TEXT NOT NULL,
    summary TEXT,  -- 'Pool + treadmill'
    address TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    price_level SMALLINT,  -- $..$$$$ for food
    day_pass_cents INTEGER,  -- 0 = free / membership
    amenities TEXT[],
    hours JSONB,  -- per-weekday open/close minutes
    photo_url TEXT,
    reservable_via reservation_provider,
    fetched_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (place_id),
    UNIQUE (provider_ref)
);

-- One area, and the last attempt to fill it from the provider.
-- `places.fetched_at` makes staleness a property of a ROW, which cannot
-- answer the question that costs money: has anyone ever looked here? An area
-- with no rows and an area that is genuinely empty are the same absence, so
-- the cheap proxy "is there a fresh row near this point" refetches an empty
-- neighbourhood on every planning run forever. Written only when a fetch was
-- actually attempted. A declined fetch leaves no row, because a row here is
-- a claim about the provider, not about us.
CREATE TABLE area_fills (
    area_fill_id UUID DEFAULT gen_random_uuid() NOT NULL,
    area_key TEXT NOT NULL,  -- rounded lat/lng, radius, kinds
    outcome area_fill_outcome NOT NULL,
    result_count SMALLINT DEFAULT 0 NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (area_fill_id),
    UNIQUE (area_key)
);

-- Street, water and park geometry for one area, cached as drawn. The Explore
-- map is a real map or it is a diagram of dots, and the difference is this
-- table. OpenStreetMap gives the geometry away, so unlike `area_fills` the
-- ceiling here is politeness to a community server rather than money --
-- which is why there is no outcome enum: nothing bills, so a failed attempt
-- costs only the retry. Geometry is stored in degrees, not pixels. The map's
-- scale is content-dependent -- it changes the moment a category chip hides
-- the furthest pin -- so a cached projection would be stale before the first
-- tap.
CREATE TABLE basemap_areas (
    basemap_area_id UUID DEFAULT gen_random_uuid() NOT NULL,
    area_key TEXT NOT NULL,  -- rounded lat/lng and radius
    roads_major JSONB NOT NULL,  -- motorway/trunk/primary
    roads_minor JSONB NOT NULL,  -- secondary/tertiary
    water JSONB NOT NULL,  -- closed rings
    parks JSONB NOT NULL,  -- closed rings
    buildings JSONB NOT NULL,  -- closed rings, close zooms only
    fetched_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (basemap_area_id),
    UNIQUE (area_key)
);

-- One row per user. Drives Explore filters, plan ranking, and the "Matched
-- from your profile" provenance chips.
CREATE TABLE user_preferences (
    user_id UUID NOT NULL,
    dietary TEXT[] DEFAULT '{}'::text[] NOT NULL,  -- {'vegetarian'}
    activities TEXT[] DEFAULT '{}'::text[] NOT NULL,  -- {'swim','running'}
    amenities TEXT[] DEFAULT '{}'::text[] NOT NULL,  -- {'pool','treadmill'}
    memberships TEXT[] DEFAULT '{}'::text[] NOT NULL,  -- {'ymca_reciprocity','hotel_gym'}
    price_level_max SMALLINT,  -- 2 = "$$ or less"
    day_pass_budget_cents INTEGER,  -- $20 cap in the demo
    session_min_minutes SMALLINT,  -- 45-90 min preference
    session_max_minutes SMALLINT,
    allow_calendar_write BOOLEAN DEFAULT false NOT NULL,
    allow_auto_book BOOLEAN DEFAULT false NOT NULL,
    watch_schedule BOOLEAN DEFAULT true NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    preferred_times TEXT[] DEFAULT '{}'::text[] NOT NULL,  -- {'mornings'}
    target_sessions SMALLINT,  -- how many sessions the traveler wants across a trip, not per day
    PRIMARY KEY (user_id),
    FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

-- OAuth grants. The token itself is held by the token store; only its
-- reference is here, so the storage backend can change without a migration.
CREATE TABLE connected_sources (
    source_id UUID DEFAULT gen_random_uuid() NOT NULL,
    user_id UUID NOT NULL,
    kind source_kind NOT NULL,
    status source_status NOT NULL,
    scopes TEXT[] DEFAULT '{}'::text[] NOT NULL,
    secret_ref TEXT,  -- Opaque token-store reference; only the store that minted it may parse it
    last_synced_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (source_id),
    CONSTRAINT connected_sources_user_id_kind_key UNIQUE (user_id, kind),
    CONSTRAINT connected_sources_check CHECK (status <> 'connected'::source_status or secret_ref is not null),
    FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

-- Long-lived secrets, encrypted at rest, addressed only by reference. A
-- separate table rather than a column on `connected_sources` because the
-- reference has to stay meaningful when the backend is not this table: a
-- caller holding `secret_ref` must not care which store answers it.
CREATE TABLE stored_secrets (
    secret_id UUID DEFAULT gen_random_uuid() NOT NULL,
    user_id UUID NOT NULL,
    kind TEXT NOT NULL,  -- What the secret is for, e.g. google_refresh_token
    nonce BYTEA NOT NULL,  -- AES-GCM nonce, freshly generated on every write
    ciphertext BYTEA NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (secret_id),
    CONSTRAINT stored_secrets_user_id_kind_key UNIQUE (user_id, kind),
    FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

-- Identity: one contiguous period of displacement from home. The
-- destination_*/timezone/hotel_* columns are the single stay, denormalized;
-- the one-stay cap is a temporary restriction, not the definition. Lifting
-- it adds a trip_stays child table, not a redefinition.
CREATE TABLE trips (
    trip_id UUID DEFAULT gen_random_uuid() NOT NULL,
    user_id UUID NOT NULL,
    destination_city TEXT NOT NULL,
    destination_region TEXT,
    destination_lat DOUBLE PRECISION,
    destination_lng DOUBLE PRECISION,
    timezone TEXT NOT NULL,  -- IANA, e.g. America/Chicago
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    label TEXT,  -- 'Conference trip'
    hotel_name TEXT,  -- 'The Gwen'
    hotel_address TEXT,
    hotel_lat DOUBLE PRECISION,
    hotel_lng DOUBLE PRECISION,
    hotel_place_id UUID,
    state trip_state DEFAULT 'detected'::trip_state NOT NULL,
    origin trip_origin NOT NULL,
    detection_confidence REAL,  -- calendar-detected trips
    activation_at TIMESTAMP WITH TIME ZONE,  -- T-7d wake-up; scheduler scans this
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (trip_id),
    CONSTRAINT trips_check CHECK (end_date >= start_date),
    FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT trips_hotel_place_fk FOREIGN KEY(hotel_place_id) REFERENCES places (place_id)
);

CREATE INDEX trips_activation_idx ON trips (state, activation_at) WHERE state in ('confirmed', 'upcoming');

CREATE INDEX trips_user_state_idx ON trips (user_id, state);

-- A free interval the agent found ("5:30 PM · 90 minutes free").
CREATE TABLE wellness_windows (
    window_id UUID DEFAULT gen_random_uuid() NOT NULL,
    trip_id UUID NOT NULL,
    local_date DATE NOT NULL,  -- trip-timezone day
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    label TEXT NOT NULL,  -- '90 minutes free'
    gap_explanation TEXT,  -- 'Between your workshop and dinner…'
    bounds JSONB DEFAULT '[]'::jsonb NOT NULL,
    status window_status DEFAULT 'open'::window_status NOT NULL,
    computed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (window_id),
    CONSTRAINT wellness_windows_check CHECK (ends_at > starts_at),
    FOREIGN KEY(trip_id) REFERENCES trips (trip_id) ON DELETE CASCADE
);

CREATE INDEX wellness_windows_trip_idx ON wellness_windows (trip_id, local_date);

-- "Based on" list in trip detection: flight event, hotel email, conference
-- events. Stores summaries + source refs, never raw email bodies.
CREATE TABLE trip_evidence (
    evidence_id UUID DEFAULT gen_random_uuid() NOT NULL,
    trip_id UUID NOT NULL,
    kind TEXT NOT NULL,  -- 'flight_event','hotel_email',...
    source_label TEXT NOT NULL,  -- 'Calendar', 'Email'
    summary TEXT NOT NULL,  -- 'UA 1142 · SFO to ORD'
    source_ref TEXT,  -- external event/message id
    detected_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    detail TEXT,
    PRIMARY KEY (evidence_id),
    FOREIGN KEY(trip_id) REFERENCES trips (trip_id) ON DELETE CASCADE
);

CREATE INDEX trip_evidence_trip_idx ON trip_evidence (trip_id);

-- Trip-relevant calendar cache: derived display fields, no raw payloads.
CREATE TABLE calendar_events (
    cal_event_id UUID DEFAULT gen_random_uuid() NOT NULL,
    user_id UUID NOT NULL,
    source_id UUID NOT NULL,
    trip_id UUID,
    external_id TEXT NOT NULL,  -- provider event id
    title TEXT NOT NULL,
    location TEXT,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT DEFAULT 'confirmed'::text NOT NULL,  -- provider status
    content_hash TEXT NOT NULL,  -- change detection on sync
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    busy BOOLEAN,  -- Does this block time? NULL = not yet classified, which is not 'free'
    PRIMARY KEY (cal_event_id),
    CONSTRAINT calendar_events_source_id_external_id_key UNIQUE (source_id, external_id),
    FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    FOREIGN KEY(source_id) REFERENCES connected_sources (source_id) ON DELETE CASCADE,
    FOREIGN KEY(trip_id) REFERENCES trips (trip_id) ON DELETE CASCADE
);

CREATE INDEX calendar_events_trip_time_idx ON calendar_events (trip_id, starts_at);

CREATE INDEX calendar_events_user_time_idx ON calendar_events (user_id, starts_at);

-- Trace root: every inbound trigger lands here before anything runs.
CREATE TABLE agent_events (
    event_id UUID DEFAULT gen_random_uuid() NOT NULL,
    user_id UUID NOT NULL,
    trip_id UUID,
    kind event_kind NOT NULL,
    payload JSONB DEFAULT '{}'::jsonb NOT NULL,  -- transcript, changed-event delta, …
    disposition event_disposition DEFAULT 'pending'::event_disposition NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    idempotency_key UUID,  -- client-generated; a retry lands on the event that already exists
    PRIMARY KEY (event_id),
    CONSTRAINT agent_events_idempotency_uq UNIQUE (user_id, idempotency_key),
    FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    FOREIGN KEY(trip_id) REFERENCES trips (trip_id) ON DELETE CASCADE
);

CREATE INDEX agent_events_disposition_idx ON agent_events (disposition) WHERE disposition = 'pending'::event_disposition;

CREATE INDEX agent_events_trip_time_idx ON agent_events (trip_id, occurred_at DESC);

-- One agent workflow execution; context_snapshot is the exact model input.
CREATE TABLE agent_runs (
    run_id UUID DEFAULT gen_random_uuid() NOT NULL,
    trip_id UUID,
    trigger_event_id UUID,
    kind run_kind NOT NULL,
    status run_status DEFAULT 'running'::run_status NOT NULL,
    context_snapshot JSONB,
    result JSONB,
    model TEXT,  -- model id used
    error TEXT,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (run_id),
    FOREIGN KEY(trip_id) REFERENCES trips (trip_id) ON DELETE CASCADE,
    FOREIGN KEY(trigger_event_id) REFERENCES agent_events (event_id)
);

CREATE INDEX agent_runs_trip_idx ON agent_runs (trip_id, started_at DESC);

-- A generated plan version. Re-planning creates a new version and marks the
-- old one superseded - history is kept for the audit trail.
CREATE TABLE plans (
    plan_id UUID DEFAULT gen_random_uuid() NOT NULL,
    trip_id UUID NOT NULL,
    version INTEGER NOT NULL,
    status plan_status DEFAULT 'proposed'::plan_status NOT NULL,
    headline TEXT,  -- 'Room for 3 workouts and a dinner'
    provenance_summary TEXT,  -- 'From your calendar and hotel email'
    generated_by_run_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (plan_id),
    CONSTRAINT plans_trip_id_version_key UNIQUE (trip_id, version),
    FOREIGN KEY(trip_id) REFERENCES trips (trip_id) ON DELETE CASCADE,
    CONSTRAINT plans_run_fk FOREIGN KEY(generated_by_run_id) REFERENCES agent_runs (run_id)
);

CREATE INDEX plans_trip_idx ON plans (trip_id, status);

-- Outbound notifications ("Your schedule changed", "Plan ready").
CREATE TABLE notifications (
    notification_id UUID DEFAULT gen_random_uuid() NOT NULL,
    user_id UUID NOT NULL,
    trip_id UUID,
    run_id UUID,
    kind TEXT NOT NULL,  -- 'plan_ready','schedule_conflict',…
    title TEXT NOT NULL,
    body TEXT,
    cta JSONB,  -- {label, deep_link}
    status notification_status DEFAULT 'pending'::notification_status NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE,
    opened_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (notification_id),
    FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    FOREIGN KEY(trip_id) REFERENCES trips (trip_id) ON DELETE CASCADE,
    FOREIGN KEY(run_id) REFERENCES agent_runs (run_id)
);

CREATE INDEX notifications_user_idx ON notifications (user_id, status, created_at DESC);

-- One recommendation slot: "YMCA at 5:30", "Beatrix at 7:30". The timeline
-- screen = calendar_events UNION plan_items ordered by time.
CREATE TABLE plan_items (
    item_id UUID DEFAULT gen_random_uuid() NOT NULL,
    plan_id UUID NOT NULL,
    trip_id UUID NOT NULL,
    window_id UUID,
    kind item_kind NOT NULL,
    status item_status DEFAULT 'suggested'::item_status NOT NULL,
    scheduled_start TIMESTAMP WITH TIME ZONE NOT NULL,
    scheduled_end TIMESTAMP WITH TIME ZONE,
    needs_reservation BOOLEAN DEFAULT false NOT NULL,
    calendar_event_ref TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (item_id),
    FOREIGN KEY(plan_id) REFERENCES plans (plan_id) ON DELETE CASCADE,
    FOREIGN KEY(trip_id) REFERENCES trips (trip_id) ON DELETE CASCADE,
    FOREIGN KEY(window_id) REFERENCES wellness_windows (window_id)
);

CREATE INDEX plan_items_trip_status_idx ON plan_items (trip_id, status);

CREATE INDEX plan_items_window_idx ON plan_items (window_id);

-- Every candidate the agent considered for a slot - selected, alternatives
-- ("Other options" sheet), and rejected ones with the reason shown in "Also
-- considered". Swapping = flipping option_state, no data loss.
CREATE TABLE plan_item_options (
    option_id UUID DEFAULT gen_random_uuid() NOT NULL,
    item_id UUID NOT NULL,
    place_id UUID,
    state option_state NOT NULL,
    rank SMALLINT DEFAULT 0 NOT NULL,
    display_name TEXT NOT NULL,  -- denormalized for stable display
    display_summary TEXT,  -- 'Pool + treadmill · 75 min'
    reason TEXT,  -- 'Fits your 90-minute opening'
    rejection_reason TEXT,  -- '$$$, above the budget you set'
    distance_minutes SMALLINT,
    duration_minutes SMALLINT,
    matched_preferences TEXT[] DEFAULT '{}'::text[] NOT NULL,  -- {'swim','45-90 min'}
    PRIMARY KEY (option_id),
    CONSTRAINT plan_item_options_check CHECK ((state = 'rejected'::option_state) = (rejection_reason is not null)),
    FOREIGN KEY(item_id) REFERENCES plan_items (item_id) ON DELETE CASCADE,
    FOREIGN KEY(place_id) REFERENCES places (place_id)
);

CREATE INDEX plan_item_options_item_idx ON plan_item_options (item_id, state, rank);

CREATE UNIQUE INDEX plan_item_options_selected_uq ON plan_item_options (item_id) WHERE state = 'selected'::option_state;

-- Every external side effect the app performs, durable and auditable.
-- Nothing books, cancels or writes a calendar directly: a caller proposes, a
-- user approves, and the executor claims the row and carries it out. That is
-- why `proposed_payload` is what *will* be done rather than what was -- the
-- row is written before the effect exists, so a crash mid-execution leaves a
-- claim to resume rather than an effect nobody recorded.
CREATE TABLE pending_actions (
    action_id UUID DEFAULT gen_random_uuid() NOT NULL,
    trip_id UUID NOT NULL,
    user_id UUID NOT NULL,
    type action_type NOT NULL,
    status action_status DEFAULT 'proposed'::action_status NOT NULL,
    approval_required BOOLEAN DEFAULT true NOT NULL,
    subject_item_id UUID,
    proposed_payload JSONB NOT NULL,  -- what will be done, exactly
    execution_result JSONB,  -- what the tool reported
    verification JSONB,  -- what we re-read to confirm
    idempotency_key TEXT,  -- retry safety
    proposed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    approved_at TIMESTAMP WITH TIME ZONE,
    executed_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (action_id),
    CONSTRAINT pending_actions_check CHECK (status not in ('completed') or (execution_result is not null)),
    FOREIGN KEY(trip_id) REFERENCES trips (trip_id) ON DELETE CASCADE,
    FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    FOREIGN KEY(subject_item_id) REFERENCES plan_items (item_id),
    UNIQUE (idempotency_key)
);

CREATE INDEX pending_actions_status_idx ON pending_actions (status) WHERE status in ('proposed', 'approved', 'executing');

CREATE INDEX pending_actions_trip_idx ON pending_actions (trip_id);

-- Reservation record - created by a completed make_reservation action, or in
-- 'failed' with failure_reason when the provider declines the hold (the
-- "Beatrix declined the 7:30 hold" flow). Never 'confirmed' until the
-- provider's confirmation is verified.
CREATE TABLE reservations (
    reservation_id UUID DEFAULT gen_random_uuid() NOT NULL,
    trip_id UUID NOT NULL,
    item_id UUID,
    place_id UUID,
    provider reservation_provider NOT NULL,
    status reservation_status DEFAULT 'pending'::reservation_status NOT NULL,
    slot_at TIMESTAMP WITH TIME ZONE NOT NULL,
    party_size SMALLINT DEFAULT 1 NOT NULL,
    confirmation_code TEXT,  -- '#4F21B'
    failure_reason TEXT,
    external_url TEXT,  -- OpenTable fallback link
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (reservation_id),
    CONSTRAINT reservations_check CHECK (status <> 'confirmed'::reservation_status or confirmation_code is not null),
    FOREIGN KEY(trip_id) REFERENCES trips (trip_id) ON DELETE CASCADE,
    FOREIGN KEY(item_id) REFERENCES plan_items (item_id) ON DELETE SET NULL,
    FOREIGN KEY(place_id) REFERENCES places (place_id)
);

CREATE INDEX reservations_trip_idx ON reservations (trip_id, status);
